### ISSUE TITLE
Upřesnění instrukcí ke stažení 

### ISSUE THREAD

**Issue by Ersmipe** [rimuln/pravidla-chs#5]
**Issue**

Bez přihlášení se odkaz na download zipu v build action chová jako prostý text bez jakéhokoliv upozornění na nutnost přihlášení, což je pro technicky méně zdatné matoucí.

**Solution**

Přidat do readme upozornění na nutnost přihlášení, nebo zpřístupnit soubor i pro návštěvníky.

**Comment by rimuln** [comment]
Tady se predpokladaji, zkuseni uzivatele, kteri vi jak GitHub pracuje. oficialni verze pro vsechny jsou na strankach https://www.horosvaz.cz/pravidla-sportovniho-lezeni/, kde je moznost vse stahnout
